; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
; Чтобы запретить PlatformIO и ESP-IDF тратить время на проверку библиотек и избегать ошибок с файлами манифестов, добавь в свой файл platformio.ini (в секцию твоего env) системную переменную для отключения менеджера компонентов
build_flags = 
    -DIDF_COMPONENT_MANAGER=0